# `readxl` {#readxl}
Note for Allison: the `{#readxl}` above lets us reference it from another chapter...not sure how much we'll use it but it's possible (and doesn't hurt to have). Cool, thanks Julie! 

## Summary (a few sentences)

The **readxl** package makes it easy to import tabular data from Excel spreadsheets (.xls or .xlsx files) and includes several options for cleaning data during import. **readxl** has no external dependencies and functions on any operating system, making it an OS- and user-friendly package that simplifies getting your data from Excel into R. 

## Objectives (more detailed, bulletpoints?)

1. Use readxl::read_excel() to read in an Excel worksheet
2. Use readxl::read_excel() to read in parts of a worksheet (by cell range)
3. Specify column names when importing Excel data
4. Replace a specific string/value with 'NA' 
5. Skip *n* rows when importing an Excel worksheet
6. Read in multiple Excel worksheets (note to Julie: I actually think this is fine to include...purrr::map() can be explained in a really simple way)
7. Something about readxl workflows (e.g. %>% write_csv())

## Resources

- https://readxl.tidyverse.org/

## Lessons teaching for each objective….. (objectives, examples)
## Fun facts (quirky things) - making a note of these wherever possible for interest (little “Did you know?” sections)
## Interludes (deep thoughts/openscapes)
## Our Turn Your Turn 1
## Our Turn Your Turn 2
## Efficiency Tips

